/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2019-12-20 07:12:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.board.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class write_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\tbody {   \r\n");
      out.write("      font-family: 'Open Sans', NanumGothic,'Malgun Gothic', Dotum, sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\t#wrap_write {\r\n");
      out.write("\t\tmargin: 100px 0 100px 0;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#wrap_write #container {\r\n");
      out.write("\t\tmargin: 0 auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#wrap_write .title_area {\r\n");
      out.write("\t\tmargin: 53px 0 50px;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#wrap_write .title_area h2 {\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t    letter-spacing: .3px;\r\n");
      out.write("\t    padding: 0 2px;\r\n");
      out.write("\t    position: relative;\r\n");
      out.write("\t    color: #00a0e2;\r\n");
      out.write("\t    font-weight: 900;\r\n");
      out.write("\t    font-size: 30px;\r\n");
      out.write("\t    border-bottom: solid 3px #00a0e2;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#wrap_write .write_area {\r\n");
      out.write("\t\tmargin: 0 auto;\r\n");
      out.write("\t\twidth: 85%;\r\n");
      out.write("\t}\t\r\n");
      out.write("\t\r\n");
      out.write("\t#wrap_write .write_area form {\r\n");
      out.write("\t\tmargin: 0 auto;\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\tpadding: 30px 0 30px 0;\r\n");
      out.write("\t\tborder: solid 1px #000000;\r\n");
      out.write("\t\tborder-top: solid 4px #000000;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#wrap_write .write_area form > div {\r\n");
      out.write("\t\twidth: 90%;\r\n");
      out.write("\t\tmargin: 0 auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#wrap_write .write_area form ul {\r\n");
      out.write("\t\tpadding: 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#wrap_write .write_area form li {\r\n");
      out.write("\t\tmargin: 0 auto;\r\n");
      out.write("\t\twidth: 90%;\r\n");
      out.write("\t\tlist-style-type: none;\r\n");
      out.write("\t\tline-height: 300%;\r\n");
      out.write("\t\tborder-bottom: solid 1px #e6e6e6;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#wrap_write .write_area form li > label {\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t\twidth: 200px;\r\n");
      out.write("\t\tfont-weight: bold;\r\n");
      out.write("\t\tfont-size: 13pt;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#wrap_write .write_area form li div {\r\n");
      out.write("\t\tdisplay: inline;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#wrap_write .write_area form li div label {\r\n");
      out.write("\t\twidth: 50px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#wrap_write .write_area form li div input { \r\n");
      out.write("\t\tmargin-right: 30px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#wrap_write .write_area form textarea {\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\theight: 200px;\r\n");
      out.write("\t\tpadding: 15px; \r\n");
      out.write("\t\tfont-size: 12pt;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#wrap_write .write_area form input[type=file] {\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t\tline-height: 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#wrap_write .write_area form input[type=password], input[type=text] {\r\n");
      out.write("\t\tline-height: 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#wrap_write .write_area form input[type=password], input[type=text], select {\r\n");
      out.write("\t\tpadding: 6px 16px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#wrap_write .write_area form input[type=password], input[type=text], select, textarea {\r\n");
      out.write("\t\tborder-radius: 4px;\r\n");
      out.write("\t\tborder: solid 1px #000000;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#wrap_write .btn_area {\r\n");
      out.write("\t\tmargin: 0 auto;\r\n");
      out.write("\t\twidth: 85%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#wrap_write .btn_area button {\r\n");
      out.write("\t\twidth: 100px;\r\n");
      out.write("\t\theight:40px;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t\tfont-size: 12pt;\r\n");
      out.write("\t\tfont-weight: bold;\r\n");
      out.write("\t\tbackground-color: #000000;\r\n");
      out.write("\t\tmargin: 30px 0 30px 0;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t\tborder: none;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#wrap_write .btn_area .btnr {\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t\tfloat: right;\r\n");
      out.write("\t\tmargin-left: 10px;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar boardNo = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(boardNo=='2'){\r\n");
      out.write("\t\t\t$(\".title_area\").html(\"<h2>Q&A</h2>\");\r\n");
      out.write("\t\t\t$(\"#subject\").hide();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(boardNo=='3'){\r\n");
      out.write("\t\t\t$(\".title_area\").html(\"<h2>REVIEW</h2>\");\r\n");
      out.write("\t\t\t$(\"#select\").hide();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#write_finish\").click(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar frm = document.writeFrm;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(boardNo == '3'){\r\n");
      out.write("\t\t\t\tif( $(\"#subject\").val().trim() == \"\" ){\r\n");
      out.write("\t\t            alert(\"글 제목을 입력해주세요 :)\");\r\n");
      out.write("\t\t            $(\"#subject\").focus();\r\n");
      out.write("\t\t            return false;\r\n");
      out.write("\t\t         }\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif( $(\"#content\").val().trim() == \"\" ){\r\n");
      out.write("\t\t\t\talert(\"글 내용을 입력해주세요 :)\");\r\n");
      out.write("\t\t\t\t$(\"#content\").focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif( $(\"#conPwd\").val().trim() == \"\" ){\r\n");
      out.write("\t\t\t\talert(\"비밀번호를 입력해주세요 ! 글은 비공개로 게시되며 글수정 및 삭제에 비밀번호가 필요합니다 :)\");\r\n");
      out.write("\t\t\t\t$(\"#conPwd\").focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar regExp = /^[0-9]{4}$/;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar bool = regExp.test($(\"#conPwd\").val().trim());\r\n");
      out.write("\t\t\tif(!bool){\r\n");
      out.write("\t\t\t\talert(\"비밀번호는 숫자 4자리로만 작성해주세요 :)\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfrm.action=\"/Semi/board/product/write.sa\";\r\n");
      out.write("\t\t\tfrm.method=\"POST\";\r\n");
      out.write("\t\t\tfrm.submit();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t}); // end of $(document).ready(function() --------------\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div id=\"wrap_write\">\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t\t<div class=\"title_area\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contentForEditMap == null || contentForEditMap != null}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t<div class=\"write_area\">\r\n");
      out.write("\t\t\t\t<form name=\"writeFrm\" enctype=\"multipart/form-data\">\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"contents\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>제 목</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select id=\"select\" name=\"select\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"상품문의\">상품문의</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"배송문의\">배송문의</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"교환/반품문의\">교환/반품문의</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"주문변경/취소문의\">주문변경/취소문의</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"입금확인문의\">입금확인문의</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"해외배송문의\">해외배송문의</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"기타문의\">기타문의</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" style=\"width: 100%;\" id=\"subject\" name=\"subject\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contentForEditMap.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>내 용</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<textarea id=\"content\" name=\"content\" style=\"width: 100%; height: 200px; padding: 15px; font-size: 12pt;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contentForEditMap.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>첨부파일 1</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"file\" name=\"bImage1\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>첨부파일 2</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"file\" name=\"bImage2\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>첨부파일 3</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"file\" name=\"bImage3\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>첨부파일 4</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"file\" name=\"bImage4\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>첨부파일 5</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"file\" name=\"bImage5\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>비밀번호</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" id=\"conPwd\" name=\"conPwd\" maxlength=\"4\" placeholder=\"숫자 4자리 입력\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"boardNo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"idx\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contentForEditMap.idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"prodcode\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prodcode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"fk_qnaidx\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contentForEditMap.fk_qnaidx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"btn_area\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goBackURL2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\">목 록</button>\r\n");
      out.write("\t\t\t\t<button type=\"reset\" class=\"btnr\" onclick=\"javascript:history.back();\">취 소</button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" id=\"write_finish\" class=\"btnr\">등 록</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</c:if>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
