/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2019-12-19 11:53:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.purchase;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class purchaseWrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1572935174000L));
    _jspx_dependants.put("jar:file:/C:/myjsp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Semi_Team1/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 String ctxPath = request.getContextPath(); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../header_dog.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.purchaseMenu {\r\n");
      out.write("\t\t display: inline-block; \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.cate2 {\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t\tfont-family: 'Notokr', sans-serif;\r\n");
      out.write("  \t\tcolor: #b3b3b3;\r\n");
      out.write("  \t\tfont-size: 13px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.cate3 {\r\n");
      out.write("\t\tborder: solid 1px gray;\r\n");
      out.write("\t\twidth: 2%;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\theight: 50px;\r\n");
      out.write("\t\tfont-family: 'Notokr';\r\n");
      out.write("\t\tfont-size: 15px;\r\n");
      out.write("    \tcolor: #777;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.pageBar {\r\n");
      out.write("\t\tclear: both;\r\n");
      out.write("\t\tmargin: 4% 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.Ha_img {\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.Ha_content {\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t\twidth: 50%;\r\n");
      out.write("\t\tborder: 1px solid #ebebeb;\r\n");
      out.write("\t\tmargin-bottom: 5%;\r\n");
      out.write("\t\tpadding-bottom: 3%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t.prd_name {\r\n");
      out.write("\t\tfont-family: 'Notokr', sans-serif;\r\n");
      out.write(" \t    font-size: 15px;\r\n");
      out.write("        color: #1c1c1c;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.prd_price {\r\n");
      out.write("\t\t color: #000;\r\n");
      out.write("   \t\t font-size: 15px;\r\n");
      out.write("  \t \t font-family: 'Lato', sans-serif;\r\n");
      out.write("  \t \t margin-top: 10%;\r\n");
      out.write("  \t \t margin-bottom: 10%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.Ha_inline {\r\n");
      out.write("\t\tdisplay: inline-block; \r\n");
      out.write("\t\tfont-size: 12px; \r\n");
      out.write("\t\tfont-family: 'Notokr';\r\n");
      out.write("\t\tcolor: #858585; \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.Ha_content_container {\r\n");
      out.write("\t\tmargin-bottom: 3%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.Ha_mabo2 {\r\n");
      out.write("\t\tmargin-bottom: 2%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.td_left {\r\n");
      out.write("\t\ttext-align: left;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.ha_weight { \r\n");
      out.write("\t\tfont-weight: 100;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.error {\r\n");
      out.write("\t\tcolor: red;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( ctxPath);
      out.write("/jquery-ui-1.11.4.custom/jquery-ui.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print( ctxPath);
      out.write("/jquery-ui-1.11.4.custom/jquery-ui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".error\").hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.insert}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"!=\"\"){\r\n");
      out.write("\t\t\talert(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.insert}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".spinner\").spinner();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".spinnerAttach\").bind(\"spinstop\", function(){\r\n");
      out.write("\t\t\tvar html = \"\";\r\n");
      out.write("\t\t\tvar cnt = $(this).val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(cnt == \"0\") {\r\n");
      out.write("\t\t\t\t$(\"#divfileattach\").empty();\r\n");
      out.write("\t\t\t\t$(\"#attachCount\").val(\"\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse {\r\n");
      out.write("\t\t\t\tfor(var i=0; i<parseInt(cnt); i++) {\r\n");
      out.write("\t\t\t\t\thtml += \"<br><input type='file' name='attach\"+i+\"'/>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\"#divfileattach\").empty();\r\n");
      out.write("\t\t\t\t$(\"#divfileattach\").append(html);\r\n");
      out.write("\t\t\t\t$(\"#attachCount\").val(cnt);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});// spinstop\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".Ha_price\").keydown(function(event){\r\n");
      out.write("\t\t\tif(event.keyCode==13){\r\n");
      out.write("\t\t\t\t$(\"#Ha_writeBtn\").click();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//return false 다른 명령 없이 위의 명령만 실행함 \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}); \r\n");
      out.write("\t\t\r\n");
      out.write("\t$(\"#Ha_writeBtn\").click(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar flag = false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".regiData\").each(function(){\r\n");
      out.write("\t\t\tvar val = $(this).val().trim();\r\n");
      out.write("\t\t\tif(val==\"\"||val==0) {\r\n");
      out.write("\t\t\t\t$(this).next().show();\r\n");
      out.write("\t\t\t\tflag = true;\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}// if\r\n");
      out.write("\t\t}); // each\r\n");
      out.write("\r\n");
      out.write("\t\tif(!flag) {\r\n");
      out.write("\t\t\tvar frm = document.contentWritefrm;\r\n");
      out.write("\t\t\tfrm.method=\"POST\";\r\n");
      out.write("\t\t\tfrm.action=\"");
      out.print( ctxPath );
      out.write("/purchase/purchaseInsert.dog\";\r\n");
      out.write("\t\t\tfrm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t}); // click\r\n");
      out.write("\t}); // ready\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div style=\"width:80%; margin: 0 auto;\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div style=\"padding: 5% 0;\">\t\t\r\n");
      out.write("\t\t<div style=\"font-family: 'Notokr'; font-size: 46px; text-align: center; font-weight: bold;\">\r\n");
      out.write("\t\t\t제품등록\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div style=\"text-align: center;\">\r\n");
      out.write("\t\t<div class='Ha_content'> \r\n");
      out.write("\t\t\t<div> \t\t\t \r\n");
      out.write("\t\t\t\t<img class='Ha_img' src='http://www.harimpetfood.com/shopimages/harimpet/0010020000032.jpg?1560151945'>  \t\t\t\t\t\t\t\t\t\t\t\t<!-- 기본이미지와 파일첨부 -->\t\r\n");
      out.write("\t\t\t</div> \r\n");
      out.write("\t\t\t<form name=\"contentWritefrm\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>브랜드</th>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_left\">\r\n");
      out.write("\t\t\t\t\t\t<select name=\"Ha_brand\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">네추럴 발란스</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">아미오</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"3\">바우와우</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"4\">이즈칸</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>고기</th>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_left\">\r\n");
      out.write("\t\t\t\t\t\t<select name=\"Ha_meat\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">닭</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">소</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"3\">연어</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"4\">양</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"5\">오리</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>수량</th>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_left\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"spinner regiData\" value=\"0\" name=\"quantity\" style=\"width: 30px; height: 20px;\" min=\"0\" max=\"1000\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"error\">필수입력!!</span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>식감</th>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_left\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"wet\" type=\"radio\" value=\"1\" name=\"texture\" class=\"regiData\"><label class=\"ha_weight\" for=\"wet\">습식</label>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<input id=\"dry\" type=\"radio\" value=\"2\" name=\"texture\" class=\"regiData\"><label class=\"ha_weight\" for=\"dry\">건식</label>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"error\">필수입력!!</span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>연령</th>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_left\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"ha_puppy\" type=\"radio\" value=\"1\" name=\"age\" class=\"regiData\"><label class=\"ha_weight\" for=\"ha_puppy\">퍼피</label>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<input id=\"ha_adult\" type=\"radio\" value=\"2\" name=\"age\" class=\"regiData\"><label class=\"ha_weight\" for=\"ha_adult\">어덜트</label>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<input id=\"ha_senior\" type=\"radio\" value=\"3\" name=\"age\" class=\"regiData\"><label class=\"ha_weight\" for=\"ha_senior\">시니어</label>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<input id=\"ha_dry\" type=\"radio\" value=\"4\" name=\"age\" class=\"regiData\"><label class=\"ha_weight\" for=\"ha_allage\">전연령</label>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"error\">필수입력!!</span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>용량(g)</th>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_left\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"regiData\" type=\"text\" name=\"capacity\" placeholder=\"ex)300\" size=\"40\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"error\">필수입력!!</span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>썸네일 사진</th>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_left\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"regiData\" type=\"file\" name=\"mainImg\" />\r\n");
      out.write("\t\t\t\t\t\t<span class=\"error\">필수입력!!</span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>내용 사진</th>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_left\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"spinner spinnerAttach regiData\" value=\"0\" style=\"width: 30px; height: 20px;\" min=\"0\" max=\"1000\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"error\">필수입력!!</span>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"divfileattach\"></div>\r\n");
      out.write("       \t\t\t\t\t<input type=\"hidden\" name=\"attachCount\" id=\"attachCount\"/> \r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>제목</th>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_left\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"regiData\" name=\"Ha_title\" type=\"text\" placeholder=\"ex)더리얼  레시피 캐롭바나나케이크 300g\" size=\"40\" />\r\n");
      out.write("\t\t\t\t\t\t<span class=\"error\">필수입력!!</span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>가격</th>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_left\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"regiData\" name=\"Ha_price\" type=\"text\" placeholder=\"ex)11000\" size=\"40\" />\r\n");
      out.write("\t\t\t\t\t\t<span class=\"error\">필수입력!!</span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>샘플이면 체크해제!</th>\r\n");
      out.write("\t\t\t\t\t<td class=\"td_left\"><input type=\"checkbox\" name=\"sample\" value=\"0\" checked=\"checked\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\"><span id=\"Ha_writeBtn\" style=\"display: inline-block; width: 50px; border: solid 1px black; text-align: center; border-radius: 15px; color: white; background-color: black; font-size: 9pt; cursor: pointer; margin-left: 20px;\">확인</span></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../footer_dog.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
