<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

	<option value="">선택</option>                                        
	<option value="골든리트리버"  >골든리트리버</option>                                        
	<option value="그레이트 덴"  >그레이트 덴</option>                                        
	<option value="그레이하운드"  >그레이하운드</option>                                        
	<option value="꼬똥"  >꼬똥</option>                                        
	<option value="닥스훈트"  >닥스훈트</option>                                        
	<option value="달마티안"  >달마티안</option>                                        
	<option value="도벨만"  >도벨만</option>                                        
	<option value="도사견"  >도사견</option>                                        
	<option value="독일 세퍼드"  >독일 세퍼드</option>                                        
	<option value="라브라도리트리버"  >라브라도리트리버</option>                                        
	<option value="로트와일러"  >로트와일러</option>                                        
	<option value="마스티프"  >마스티프</option>                                        
	<option value="말라뮤트"  >말라뮤트</option>                                        
	<option value="말티즈"  >말티즈</option>                                        
	<option value="바셋하운드"  >바셋하운드</option>                                        
	<option value="보르조이"  >보르조이</option>                                        
	<option value="보스턴테리어"  >보스턴테리어</option>                                        
	<option value="복서"  >복서</option>                                        
	<option value="불독"  >불독</option>                                        
	<option value="불테리어"  >불테리어</option>                                        
	<option value="비글"  >비글</option>                                        
	<option value="비숑프리제"  >비숑프리제</option>                                        
	<option value="빠삐용"  >빠삐용</option>                                        
	<option value="사모예드"  >사모예드</option>                                        
	<option value="삽사리"  >삽사리</option>                                        
	<option value="세인트 버나드"  >세인트 버나드</option>                                        
	<option value="셔틀드 쉽독"  >셔틀드 쉽독</option>                                        
	<option value="소프트 코티드 휘튼 테리어"  >소프트 코티드 휘튼 테리어</option>                                        
	<option value="슈나우저"  >슈나우저</option>                                        
	<option value="스무스 폭스테리어"  >스무스 폭스테리어</option>                                        
	<option value="스피츠"  >스피츠</option>                                        
	<option value="시베리안허스키"  >시베리안허스키</option>                                        
	<option value="시츄"  >시츄</option>                                        
	<option value="실키테리어"  >실키테리어</option>                                        
	<option value="아메리칸 에스키모 도그"  >아메리칸 에스키모 도그</option>                                        
	<option value="아키다"  >아키다</option>                                        
	<option value="아프간하운드"  >아프간하운드</option>                                        
	<option value="에어데일테리어"  >에어데일테리어</option>                                        
	<option value="올드 잉글리쉬 쉽독"  >올드 잉글리쉬 쉽독</option>                                        
	<option value="와이어폭스테리어"  >와이어폭스테리어</option>                                        
	<option value="요크셔테리어"  >요크셔테리어</option>                                        
	<option value="잉글리쉬 세터"  >잉글리쉬 세터</option>                                        
	<option value="진돗개"  >진돗개</option>                                        
	<option value="치와와"  >치와와</option>                                        
	<option value="친"  >친</option>                                        
	<option value="카디건웰시코기"  >카디건웰시코기</option>                                        
	<option value="캐리블루 테리어"  >캐리블루 테리어</option>                                        
	<option value="코커스파니엘"  >코커스파니엘</option>                                        
	<option value="콜리"  >콜리</option>                                        
	<option value="퍼그"  >퍼그</option>                                        
	<option value="페키니스"  >페키니스</option>                                        
	<option value="펨브록"  >펨브록</option>                                        
	<option value="웰시 코기"  >웰시 코기</option>                                        
	<option value="포메라니언"  >포메라니언</option>                                        
	<option value="포인터"  >포인터</option>                                        
	<option value="폼피츠"  >폼피츠</option>                                        
	<option value="푸들"  >푸들</option>                                        
	<option value="푸들(토이)"  >푸들(토이)</option>                                        
	<option value="풍산개"  >풍산개</option>                                        
	<option value="핀셔"  >핀셔</option>                                        
	<option value="기타"  >기타</option>
