/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2019-12-19 09:36:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.addrPopup;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t#popupRegi {\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t\tmargin: 0 auto;\r\n");
      out.write("\t\tfont-family: 'Open Sans',NanumGothic,'Malgun Gothic',Dotum,sans-serif;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#popupRegi .header {\r\n");
      out.write("\t\tbackground-color: #495164; \r\n");
      out.write("\t\tcolor: white; \r\n");
      out.write("\t\tfont-size: 9pt; \r\n");
      out.write("\t\twidth: 100%; \r\n");
      out.write("\t\tpadding: 5px 0 5px 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#popupRegi .tableStyle1 {\r\n");
      out.write("\t\twidth: 95%;\r\n");
      out.write("\t\tmargin: 20px auto;\r\n");
      out.write("\t\tborder-collapse: collapse;\r\n");
      out.write("\t\tfont-size: 9pt;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#popupRegi .tableStyle1 tr:first-child {\r\n");
      out.write("\t\tbackground-color: #fbfafa;\r\n");
      out.write("\t\theight: 30px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#popupRegi .tableStyle1 tr td {\r\n");
      out.write("\t\tborder: solid 1px #e6e6e6;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#popupRegi .classforlist ul {\r\n");
      out.write("\t\tpadding: 15px 10px 15px 10px;\r\n");
      out.write("\t\tmargin: 0px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#popupRegi .classforlist ul li {\r\n");
      out.write("\t\tlist-style-type: none;\r\n");
      out.write("\t\tcolor: gray;\r\n");
      out.write("\t\tline-height: 150%;\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#popupRegi .tableStyle2 {\r\n");
      out.write("\t\twidth: 95%;\r\n");
      out.write("\t\tmargin: 20px auto;\r\n");
      out.write("\t\tborder-collapse: collapse;\r\n");
      out.write("\t\tfont-size: 9pt;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#popupRegi .tableStyle2 tr td {\r\n");
      out.write("\t\tborder: solid 1px #e6e6e6;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#popupRegi .tableStyle2 tr td:first-child {\r\n");
      out.write("\t\tbackground-color: #fbfafa;\r\n");
      out.write("\t\tpadding: 10px;\r\n");
      out.write("\t\twidth: 100px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#popupRegi .tableStyle2 tr td {\r\n");
      out.write("\t\tpadding: 5px 10px 4px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#popupRegi .tableStyle2 tr td input {\r\n");
      out.write("\t\tborder: solid 1px #e6e6e6;\r\n");
      out.write("\t\tpadding: 2px 4px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#popupRegi .tableStyle2 tr td select {\r\n");
      out.write("\t\twidth: 60px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#popupRegi table button {\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#popupRegi .navyBtn {\r\n");
      out.write("\t\tbackground-color: #495164; \r\n");
      out.write("\t\tpadding: 5px 10px;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t\tborder: solid 1px #e6e6e6;\r\n");
      out.write("\t\tborder-radius: 3px;\r\n");
      out.write("\t\tmargin: 5px auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#popupRegi .whiteBtn {\r\n");
      out.write("\t\tbackground-color: white; \r\n");
      out.write("\t\tpadding: 5px 10px;\r\n");
      out.write("\t\tcolor: #000000;\r\n");
      out.write("\t\tborder: solid 1px #e6e6e6;\r\n");
      out.write("\t\tborder-radius: 3px;\r\n");
      out.write("\t\tmargin: 5px auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#popupRegi .footer {\r\n");
      out.write("\t\tbackground-color: #fbfafa;\r\n");
      out.write("\t\tfont-size: 9pt; \r\n");
      out.write("\t\twidth: 100%; \r\n");
      out.write("\t\tpadding: 5px 0 5px 10px;\r\n");
      out.write("\t\tborder-top: solid 1px #e6e6e6;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#popupRegi button {\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#popupRegi .star {\r\n");
      out.write("\t\tcolor: blue;\r\n");
      out.write("\t\tfont-weight: bold;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\t\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#upNewDeli\").click(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif( $(\"#destination\").val().trim() == \"\" ){\r\n");
      out.write("\t\t\t\talert(\"배송지명은 필수 입력사항입니다.\");\r\n");
      out.write("\t\t\t\t$(\"#destination\").focus();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif( $(\"#receiver\").val().trim() == \"\" ){\r\n");
      out.write("\t\t\t\talert(\"성명은 필수 입력사항입니다.\");\r\n");
      out.write("\t\t\t\t$(\"#receiver\").focus();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif( $(\"#post\").val().trim() == \"\" ){\r\n");
      out.write("\t\t\t\talert(\"주소는 필수 입력사항입니다.\");\r\n");
      out.write("\t\t\t\t$(\"#post\").focus();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar hp2 = $(\"#hp2\").val().trim();\r\n");
      out.write("\t\t\tvar hp3 = $(\"#hp3\").val().trim();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif( \"\" == (hp2 && hp3) ){\r\n");
      out.write("\t\t\t\talert(\"휴대전화 번호는 필수 입력사항입니다.\");\r\n");
      out.write("\t\t\t\t$(\"#hp1\").focus();\r\n");
      out.write("\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar regExp1 = /^[0-9]{3,4}$/;\r\n");
      out.write("\t\t\t\tvar regExp2 = /^[0-9]{4}$/;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar bool1 = regExp1.test(hp2);\r\n");
      out.write("\t\t\t\tvar bool2 = regExp2.test(hp3);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(!bool1){\r\n");
      out.write("\t\t\t\t\talert(\"휴대전화 가운데 번호는 숫자 3~4자리로만 입력해주세요.\");\r\n");
      out.write("\t\t\t\t\t$(\"#hp2\").focus();\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\telse if(!bool2){\r\n");
      out.write("\t\t\t\t\talert(\"휴대전화 마지막 번호는 숫자 4자리로만 입력해주세요.\");\r\n");
      out.write("\t\t\t\t\t$(\"#hp3\").focus();\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\telse { \r\n");
      out.write("\t\t\t\t\t// 기본 배송지 여부 체크 0,1로 지정\r\n");
      out.write("\t\t\t\t\tif($(\"#addrbase\").prop(\"checked\")){\r\n");
      out.write("\t\t\t\t\t\t$(\"#addrbase\").val(\"1\");\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t$(\"#addrbase\").val(\"0\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t// 모든 값이 제대로 들어간 경우\r\n");
      out.write("\t\t\t\t\t// 주소지 수정인 경우 addrno가 null이 아니다.\r\n");
      out.write("\t\t\t\t\tvar addrno = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${addrno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar frm = document.popupDeliFrm;\r\n");
      out.write("\t\t\t\t\tfrm.method = \"POST\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(addrno== \"\"){\r\n");
      out.write("\t\t\t\t\t\t frm.action = \"/Semi/addrPopup/addrAdd.sa\";\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tfrm.action = \"/Semi/addrPopup/addrUpdate.sa\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfrm.submit();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t// 우편번호찾기 \r\n");
      out.write("\tfunction openPOST(){\r\n");
      out.write("\r\n");
      out.write("\t\tnew daum.Postcode({\r\n");
      out.write("\t\t\toncomplete: function(data) {\r\n");
      out.write("\t\t\t    $(\"#post\").val(data.postcode1+data.postcode2);\r\n");
      out.write("\t\t\t    $(\"#addr1\").val(data.address);\r\n");
      out.write("\t\t\t    $(\"#addr2\").focus();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}).open();\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<body onload=\"resizeTo(800, 650);\" id=\"popupRegi\">\r\n");
      out.write("<div class=\"header\"><h3>배송 주소록 관리</h3></div>\r\n");
      out.write("\t<table class=\"tableStyle1 classforlist\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td style=\"padding-left: 10px; font-weight: bold;\">배송주소록 유의사항</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>- 배송 주소록은 최대 10개까지 등록할 수 있으며, 별도로 등록하지 않을 경우 최근 배송 주소록 기준으로 자동 업데이트 됩니다.</li>\r\n");
      out.write("\t\t\t\t\t<li>- 자동 업데이트를 원하지 않을 경우 주소록 고정 선택을 선택하시면 선택된 주소록은 업데이트 대상에서 제외됩니다.</li>\r\n");
      out.write("\t\t\t\t\t<li>- 기본 배송지는 1개만 저장됩니다. 다른 배송지를 기본 배송지로 설정하시면 기본 배송지가 변경됩니다.</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"delivery_area\" style=\"font-size: 10pt;\">\r\n");
      out.write("\t\t<form name=\"popupDeliFrm\">\r\n");
      out.write("\t\t\t<table class=\"tableStyle2\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>배송지명&nbsp;<span class=\"star\">*</span></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"destination\" name=\"destination\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>성명&nbsp;<span class=\"star\">*</span></td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"receiver\" name=\"receiver\" required></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>주소&nbsp;<span class=\"star\">*</span></td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" id=\"post\" name=\"post\" size=\"10\" maxlength=\"5\" readonly required/>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" id=\"searchPost\" onClick=\"openPOST();\" style=\"display: inline-block;\">우편번호</button><br/>\r\n");
      out.write("\t\t\t\t\t\t <input type=\"text\" id=\"addr1\" name=\"addr1\" size=\"50\" readonly style=\"margin: 5px 0 5px 0\" placeholder=\"우편번호 서비스를 이용해주세요.\" required/> <span style=\"color: #999999\">기본주소</span><br/>\r\n");
      out.write("\t\t    \t\t\t <input type=\"text\" id=\"addr2\" name=\"addr2\" size=\"50\" required/> <span style=\"color: #999999\">나머지주소(선택입력가능)</span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>일반전화</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<select id=\"tp1\" name=\"tp1\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"02\" selected>02</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"031\">031</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"032\">032</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"033\">033</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"041\">041</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"042\">042</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"043\">043</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"044\">044</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"051\">051</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"052\">052</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"053\">053</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"054\">054</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"055\">055</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"061\">061</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"062\">062</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"063\">063</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"064\">064</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"0502\">0502</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"0503\">0503</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"0504\">0504</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"0505\">0505</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"0506\">0506</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"0507\">0507</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"070\">070</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"010\">010</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"011\">011</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"016\">016</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"017\">017</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"018\">018</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"019\">019</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t&nbsp;-&nbsp;    \r\n");
      out.write("\t\t    \t\t\t<input type=\"text\" id=\"tp2\" name=\"tp2\" size=\"5\" maxlength=\"4\" required/>&nbsp;-&nbsp;\r\n");
      out.write("\t\t    \t\t\t<input type=\"text\" id=\"tp3\" name=\"tp3\" size=\"5\" maxlength=\"4\" required/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>휴대전화&nbsp;<span class=\"star\">*</span></td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select id=\"hp1\" name=\"hp1\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"010\" selected>010</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"011\">011</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"016\">016</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"017\">017</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"018\">018</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"019\">019</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t&nbsp;-&nbsp;    \r\n");
      out.write("\t\t    \t\t\t<input type=\"text\" id=\"hp2\" name=\"hp2\" size=\"5\" maxlength=\"4\" required/>&nbsp;-&nbsp;\r\n");
      out.write("\t\t    \t\t\t<input type=\"text\" id=\"hp3\" name=\"hp3\" size=\"5\" maxlength=\"4\" required/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\" style=\"background-color: white; text-align: right;\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" id=\"addrbase\" name=\"addrbase\" value=\"0\"/>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"addrbase\">기본 배송지로 저장</label>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"addrno\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${addrno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"footer\">\r\n");
      out.write("\t\t<button type=\"button\" id=\"upNewDeli\" class=\"navyBtn\">등록</button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"whiteBtn\" onclick=\"javascript:history.back()\">취소</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
